andres/force-app/main/default/objects/Seller_Request__c/Seller_Request__c.object-meta.xml
<CustomObject>
    <description>A way to track seller requests</description>
    <label>Seller Request</label>
    <nameField>
        <displayFormat>Seller Request-{0000}</displayFormat>
        <label>Seller Request</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Seller Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

andres/force-app/main/default/objects/Seller_Request__c/fields/Car_Brand__c.field-meta.xml
<CustomField>
    <fullName>Car_Brand__c</fullName>
    <description>The sellers car brand of the car they are selling</description>
    <label>Car Brand</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Car_Brands</valueSetName>
    </valueSet>
</CustomField>

andres/force-app/main/default/objects/Seller_Request__c/fields/Model_year__c.field-meta.xml
<CustomField>
    <fullName>Model_year__c</fullName>
    <description>The model year of the sellers car</description>
    <label>Model year</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>model_year</valueSetName>
    </valueSet>
</CustomField>

andres/force-app/main/default/globalValueSets/Car_Brands.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Acura</fullName>
    </customValue>
    <customValue>
        <fullName>Alfa Romeo</fullName>
    </customValue>
    <customValue>
        <fullName>Aston Martin</fullName>
    </customValue>
    <customValue>
        <fullName>Audi</fullName>
    </customValue>
    <customValue>
        <fullName>Bentley</fullName>
    </customValue>
    <customValue>
        <fullName>BMW</fullName>
    </customValue>
    <customValue>
        <fullName>Buick</fullName>
    </customValue>
    <customValue>
        <fullName>Cadillac</fullName>
    </customValue>
    <customValue>
        <fullName>Chrysler</fullName>
    </customValue>
    <customValue>
        <fullName>Dodge</fullName>
    </customValue>
    <customValue>
        <fullName>Ferrari</fullName>
    </customValue>
    <customValue>
        <fullName>Fiat</fullName>
    </customValue>
    <customValue>
        <fullName>Ford</fullName>
    </customValue>
    <customValue>
        <fullName>Genesis</fullName>
    </customValue>
    <customValue>
        <fullName>GMC</fullName>
    </customValue>
    <customValue>
        <fullName>Honda</fullName>
    </customValue>
    <customValue>
        <fullName>Hyundai</fullName>
    </customValue>
    <customValue>
        <fullName>Infiniti</fullName>
    </customValue>
    <customValue>
        <fullName>Jaguar</fullName>
    </customValue>
    <customValue>
        <fullName>Jeep</fullName>
    </customValue>
    <customValue>
        <fullName>Kia</fullName>
    </customValue>
    <customValue>
        <fullName>Lamborghini</fullName>
    </customValue>
    <customValue>
        <fullName>Land Rover</fullName>
    </customValue>
    <customValue>
        <fullName>Lexus</fullName>
    </customValue>
    <customValue>
        <fullName>Lincoln</fullName>
    </customValue>
    <customValue>
        <fullName>Lotus</fullName>
    </customValue>
    <customValue>
        <fullName>Maserati</fullName>
    </customValue>
    <customValue>
        <fullName>Mazda</fullName>
    </customValue>
    <customValue>
        <fullName>Mercedes Benz</fullName>
    </customValue>
    <customValue>
        <fullName>Mini</fullName>
    </customValue>
    <description>A List of Major Car brands in the US</description>
    <masterLabel>Car Brands</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

andres/force-app/main/default/globalValueSets/model_year.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>2022</fullName>
    </customValue>
    <customValue>
        <fullName>2021</fullName>
    </customValue>
    <customValue>
        <fullName>2020</fullName>
    </customValue>
    <customValue>
        <fullName>2019</fullName>
    </customValue>
    <customValue>
        <fullName>2018</fullName>
    </customValue>
    <customValue>
        <fullName>2017</fullName>
    </customValue>
    <customValue>
        <fullName>2016</fullName>
    </customValue>
    <customValue>
        <fullName>2015</fullName>
    </customValue>
    <customValue>
        <fullName>2014</fullName>
    </customValue>
    <customValue>
        <fullName>2013</fullName>
    </customValue>
    <customValue>
        <fullName>2012</fullName>
    </customValue>
    <customValue>
        <fullName>2011</fullName>
    </customValue>
    <customValue>
        <fullName>2010</fullName>
    </customValue>
    <customValue>
        <fullName>2009</fullName>
    </customValue>
    <customValue>
        <fullName>2008</fullName>
    </customValue>
    <customValue>
        <fullName>2007</fullName>
    </customValue>
    <customValue>
        <fullName>2006</fullName>
    </customValue>
    <customValue>
        <fullName>2005</fullName>
    </customValue>
    <customValue>
        <fullName>2004</fullName>
    </customValue>
    <customValue>
        <fullName>2003</fullName>
    </customValue>
    <customValue>
        <fullName>2002</fullName>
    </customValue>
    <customValue>
        <fullName>2001</fullName>
    </customValue>
    <customValue>
        <fullName>2000</fullName>
    </customValue>
    <customValue>
        <fullName>1999</fullName>
    </customValue>
    <customValue>
        <fullName>1998</fullName>
    </customValue>
    <customValue>
        <fullName>1997</fullName>
    </customValue>
    <customValue>
        <fullName>1996</fullName>
    </customValue>
    <customValue>
        <fullName>1995</fullName>
    </customValue>
    <customValue>
        <fullName>1994</fullName>
    </customValue>
    <customValue>
        <fullName>1993</fullName>
    </customValue>
    <description>the model year of the car</description>
    <masterLabel>model year</masterLabel>
</GlobalValueSet>

andres/force-app/main/default/classes/sellerExtension.cls
public class sellerExtension {
    public sellerExtension(ApexPages.StandardSetController ssc){}
  	public Seller_Request__c sr { get; set;}
    public List<SelectOption> modelYears{get{
        List<Schema.PicklistEntry> sources = Schema.SObjectType.Seller_Request__c.Fields.Model_year__c.getPicklistValues();
        modelYears = new List<SelectOption>();
        for(Schema.PicklistEntry pe: sources){
            modelYears.add(new SelectOption(pe.getValue(), pe.getLabel()));
        }
        return modelYears;
    } set;}
    public List<SelectOption> carBrands{get{
        List<Schema.PicklistEntry> sources = Schema.SObjectType.Seller_Request__c.Fields.Car_Brand__c.getPicklistValues();
        carBrands = new List<SelectOption>();
        for(Schema.PicklistEntry pe: sources){
            carBrands.add(new SelectOption(pe.getValue(), pe.getLabel()));
        }
        return carBrands;
    } set;}
    public SellerExtension(){
        this.sr = new Seller_Request__c();
        }
    
}