andres/force-app/main/default/objects/Employee__c/Employee__c.object-meta.xml
<CustomObject>
    <label>Employee</label>
    <nameField>
        <label>Employee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

andres/force-app/main/default/objects/Lot__c/Lot__c.object-meta.xml
<CustomObject>
    <label>Lot</label>
    <nameField>
        <label>Lot Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Lots</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

andres/force-app/main/default/objects/Lot__c/fields/Employee__c.field-meta.xml
<CustomField>
    <fullName>Employee__c</fullName>
    <label>Employee</label>
    <referenceTo>Employee__c</referenceTo>
    <relationshipLabel>Lots</relationshipLabel>
    <relationshipName>Lots</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

andres/force-app/main/default/objects/Vehicle__c/Vehicle__c.object-meta.xml
<CustomObject>
    <label>Vehicle</label>
    <nameField>
        <label>Make and Model</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vehicles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

andres/force-app/main/default/objects/Vehicle__c/fields/Lot__c.field-meta.xml
<CustomField>
    <fullName>Lot__c</fullName>
    <label>Lot</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.Type__c</field>
            <operation>equals</operation>
            <valueField>Lot__c.Vehicle_Type__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Lot__c</referenceTo>
    <relationshipLabel>Vehicles</relationshipLabel>
    <relationshipName>Vehicles</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

andres/force-app/main/default/objects/Vehicle__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Sedan</fullName>
            </value>
            <value>
                <fullName>Coupe</fullName>
            </value>
            <value>
                <fullName>Hatchback</fullName>
            </value>
            <value>
                <fullName>Mini-van</fullName>
            </value>
            <value>
                <fullName>SUV</fullName>
            </value>
            <value>
                <fullName>Truck</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

andres/force-app/main/default/classes/HomePageControllerTests.cls
@isTest
public class HomePageControllerTests {
	@isTest
    static void emptyQueryTest(){
        Employee__c e = new Employee__c();
        Lot__c l = new Lot__c();
        Vehicle__c v1 = new Vehicle__c();
        Vehicle__c v2 = new Vehicle__c();
        Vehicle__c v3 = new Vehicle__c();
        List<Vehicle__c> vList = new List<Vehicle__c>();
        vList.add(v1);
        vList.add(v2);
        vList.add(v3);
        e.Name = 'Billy';
        e.Phone_Number__c = '1231231234';
        e.Zip_Code__c = '12345';
        insert e;
        l.Name = 'Sedan';
        Employee__c emp = [SELECT Id FROM Employee__c];
        l.Employee__c = emp.Id;
        insert l;
        Lot__c lot = [SELECT Id From Lot__c];
        for(Vehicle__c v : vList){
            v.Lot__c = lot.Id;
            v.Type__c = 'Sedan';
            v.Year__c = '2001';
        }
        insert vList;
        List<Vehicle__c> results = HomePageController.makeVehicleQuery('');
        System.assertEquals(0, results.size());
    }
    @isTest
    static void queryNoWhereClause(){
        Employee__c e = new Employee__c();
        Lot__c l = new Lot__c();
        Vehicle__c v1 = new Vehicle__c();
        Vehicle__c v2 = new Vehicle__c();
        Vehicle__c v3 = new Vehicle__c();
        List<Vehicle__c> vList = new List<Vehicle__c>();
        vList.add(v1);
        vList.add(v2);
        vList.add(v3);
        e.Name = 'Billy';
        e.Phone_Number__c = '1231231234';
        e.Zip_Code__c = '12345';
        insert e;
        l.Name = 'Sedan';
        Employee__c emp = [SELECT Id FROM Employee__c];
        l.Employee__c = emp.Id;
        insert l;
        Lot__c lot = [SELECT Id From Lot__c];
        for(Vehicle__c v : vList){
            v.Lot__c = lot.Id;
            v.Type__c = 'Sedan';
            v.Year__c = '2001';
        }
        insert vList;
        List<Vehicle__c> results = HomePageController.makeVehicleQuery('SELECT Id FROM Vehicle__c');
        System.assertEquals(3, results.size());        
    }
}