andres/force-app/main/default/objects/Employee__c/Employee__c.object-meta.xml
<CustomObject>
    <label>Employee</label>
    <nameField>
        <label>Employee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

andres/force-app/main/default/objects/Lot__c/Lot__c.object-meta.xml
<CustomObject>
    <label>Lot</label>
    <nameField>
        <label>Lot Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Lots</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

andres/force-app/main/default/objects/Lot__c/fields/Employee__c.field-meta.xml
<CustomField>
    <fullName>Employee__c</fullName>
    <label>Employee</label>
    <referenceTo>Employee__c</referenceTo>
    <relationshipLabel>Lots</relationshipLabel>
    <relationshipName>Lots</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

andres/force-app/main/default/objects/Vehicle__c/Vehicle__c.object-meta.xml
<CustomObject>
    <label>Vehicle</label>
    <nameField>
        <label>Make and Model</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vehicles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

andres/force-app/main/default/objects/Vehicle__c/fields/Listed_As__c.field-meta.xml
<CustomField>
    <fullName>Listed_As__c</fullName>
    <label>Listed As</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Sale</fullName>
            </value>
            <value>
                <fullName>Rent</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

andres/force-app/main/default/objects/Vehicle__c/fields/Lot__c.field-meta.xml
<CustomField>
    <fullName>Lot__c</fullName>
    <label>Lot</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.Type__c</field>
            <operation>equals</operation>
            <valueField>Lot__c.Vehicle_Type__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Lot__c</referenceTo>
    <relationshipLabel>Vehicles</relationshipLabel>
    <relationshipName>Vehicles</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

andres/force-app/main/default/objects/Vehicle__c/fields/Price__c.field-meta.xml
<CustomField>
    <fullName>Price__c</fullName>
    <description>Valued price of the vehicle.</description>
    <inlineHelpText>If a price is not set it will set the price to $1 as default. This is done to know that the car is for sale.</inlineHelpText>
    <label>Price</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

andres/force-app/main/default/objects/Vehicle__c/fields/Transmission__c.field-meta.xml
<CustomField>
    <fullName>Transmission__c</fullName>
    <label>Transmission</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Automatic</fullName>
            </value>
            <value>
                <fullName>Manual</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

andres/force-app/main/default/objects/Vehicle__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Sedan</fullName>
            </value>
            <value>
                <fullName>Coupe</fullName>
            </value>
            <value>
                <fullName>Hatchback</fullName>
            </value>
            <value>
                <fullName>Mini-van</fullName>
            </value>
            <value>
                <fullName>SUV</fullName>
            </value>
            <value>
                <fullName>Truck</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

andres/force-app/main/default/classes/MassInventoryExtension.cls
public class MassInventoryExtension {
    public Id vehicleId{get;set;}
    public Vehicle__c v{get;set;}
    public EmailMessage email{get;set;}
    public Decimal monthlyPrice{get{
        return monthlyPrice.setScale(2);
    }set;}
    
    public MassInventoryExtension(ApexPages.StandardSetController ssc){
        email = new EmailMessage();
    }
    
    public PageReference vehicleDetail(){
        //System.debug(vehicleId);
        v = [SELECT Id, Listed_As__c, Year__c, Name, Image__c, Type__c, Mileage__c, Transmission__c, Price__c, Lot__r.Name, Lot__r.Employee__r.Name, Lot__r.Employee__r.Phone_Number__c FROM Vehicle__c WHERE Id =: vehicleID];
        monthlyPrice = v.Price__c / 72;
        return Page.SingleCarRecordPage;
    }
    
    public PageReference massInventory(){
        return Page.MassInventory;
    }
    
    public void sendEmail(){
        try{
            insert email;
            email = new EmailMessage();
        } catch(DmlException e) {
            System.debug('The following error has occured: ' + e.getMessage());
        } 
    }
}