andres/force-app/main/default/objects/Vehicle__c/Vehicle__c.object-meta.xml
<CustomObject>
    <label>Vehicle</label>
    <nameField>
        <label>Make and Model</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vehicles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

andres/force-app/main/default/objects/Vehicle__c/fields/Price__c.field-meta.xml
<CustomField>
    <fullName>Price__c</fullName>
    <description>Valued price of the vehicle.</description>
    <inlineHelpText>If a price is not set it will set the price to $1 as default. This is done to know that the car is for sale.</inlineHelpText>
    <label>Price</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

andres/force-app/main/default/classes/MyMassInventoryListController.cls
public class MyMassInventoryListController {
    
	//Get List of Vehicles for Mass Inventory Component
	@AuraEnabled
    public static List<Vehicle__c> fetchVehicle(String searchWord){
        
        List<Vehicle__c> returnList = new List<Vehicle__c>();
        
        //if search value is null, return all vehicles
        //else return the enquiry
        String searchKey = String.isBlank(searchWord) ? '%%' : searchWord + '%';
        
        returnList = [SELECT Name, Year__c, Price__c FROM Vehicle__c WHERE Name LIKE :searchKey LIMIT 20];
        
        return returnList;
        
    }
}