andres/force-app/main/default/objects/Vehicle__c/Vehicle__c.object-meta.xml
<CustomObject>
    <label>Vehicle</label>
    <nameField>
        <label>Make and Model</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vehicles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

andres/force-app/main/default/objects/Vehicle__c/fields/Price__c.field-meta.xml
<CustomField>
    <fullName>Price__c</fullName>
    <description>Valued price of the vehicle.</description>
    <inlineHelpText>If a price is not set it will set the price to $1 as default. This is done to know that the car is for sale.</inlineHelpText>
    <label>Price</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

andres/force-app/main/default/classes/TriggerVehicleHelper.cls
public class TriggerVehicleHelper {

    //if there are any negative values we will set them to null or a default value
    public static void checkForNegativeValues(List<Vehicle__c> vehicleList){
        for(Vehicle__c vehicle : vehicleList){
            if(Integer.valueOf(vehicle.Year__c) < 0){
               // System.debug(Integer.valueOf(vehicle.Year__c));
                vehicle.Year__c = null;
            }
            /*if(vehicle.Mileage__c < 0){
                //System.debug(vehicle.Mileage__c);
                vehicle.Mileage__c = null;
            }*/
            
            
            if(vehicle.Price__c == null){
				//System.debug(vehicle.Price__c);
                vehicle.Price__c = 1;
                //vehicle.addError('Price was set to a value less than 0.');
            }
        }
    }
}