andres/force-app/main/default/objects/Lot__c/Lot__c.object-meta.xml
<CustomObject>
    <label>Lot</label>
    <nameField>
        <label>Lot Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Lots</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

andres/force-app/main/default/objects/Lot__c/fields/Vehicle_Type__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_Type__c</fullName>
    <label>Vehicle Type</label>
    <length>30</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

andres/force-app/main/default/objects/Vehicle__c/Vehicle__c.object-meta.xml
<CustomObject>
    <label>Vehicle</label>
    <nameField>
        <label>Make and Model</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vehicles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

andres/force-app/main/default/objects/Vehicle__c/fields/Lot__c.field-meta.xml
<CustomField>
    <fullName>Lot__c</fullName>
    <label>Lot</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.Type__c</field>
            <operation>equals</operation>
            <valueField>Lot__c.Vehicle_Type__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Lot__c</referenceTo>
    <relationshipLabel>Vehicles</relationshipLabel>
    <relationshipName>Vehicles</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

andres/force-app/main/default/objects/Vehicle__c/fields/Price__c.field-meta.xml
<CustomField>
    <fullName>Price__c</fullName>
    <description>Valued price of the vehicle.</description>
    <inlineHelpText>If a price is not set it will set the price to $1 as default. This is done to know that the car is for sale.</inlineHelpText>
    <label>Price</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

andres/force-app/main/default/objects/Vehicle__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Sedan</fullName>
            </value>
            <value>
                <fullName>Coupe</fullName>
            </value>
            <value>
                <fullName>Hatchback</fullName>
            </value>
            <value>
                <fullName>Mini-van</fullName>
            </value>
            <value>
                <fullName>SUV</fullName>
            </value>
            <value>
                <fullName>Truck</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

andres/force-app/main/default/classes/VehicleTest.cls
@isTest public class VehicleTest {
	
    /*@TestSetup
    static void MakeTestData(){
           
    }*/
    
    @isTest public static void testForNullPrice(){
        List<Vehicle__c> testVehicles = new List<Vehicle__c>();
        List<Lot__c> lots = [SELECT Name FROM Lot__c WHERE Vehicle_Type__c = 'Sedan'];
        String lotId;
        for(Lot__c lot : lots){
            lotId = lot.Id;
        }

		for(Integer i = 0; i < 5; i++){
            testVehicles.add(new Vehicle__c(Name = 'vehicle#'+i, Price__c = null, Mileage__c = (-1)*Math.random()*100000, Type__c = 'Sedan', Lot__c = lotId));
        }
                             
        Test.startTest();
        Database.SaveResult[] results = Database.insert(testVehicles, false);
        Test.stopTest();
   		
        for(Database.SaveResult iRes : results){
            System.assert(!iRes.isSuccess());		// checks if not successfull
        }
                     
    }
}