andres/force-app/main/default/objects/Open_Position__c/Open_Position__c.object-meta.xml
<CustomObject>
    <description>Job Positions that need to be filled</description>
    <label>Open Position</label>
    <nameField>
        <displayFormat>Job Opening-{0000}</displayFormat>
        <label>Job Opening</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Open Positions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

andres/force-app/main/default/objects/Open_Position__c/fields/Job_Title__c.field-meta.xml
<CustomField>
    <fullName>Job_Title__c</fullName>
    <label>Job Title</label>
    <length>25</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

andres/force-app/main/default/objects/Open_Position__c/fields/salary__c.field-meta.xml
<CustomField>
    <fullName>salary__c</fullName>
    <label>salary</label>
    <length>25</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

andres/force-app/main/default/objects/Open_Position__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Filled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

andres/force-app/main/default/classes/JobApexController.cls
public class JobApexController {

    /*
     * inorder to make an apex method that we can call from a Js controller we need it to be public static and have the @AuraEnabled annotation above it
     */
    
    @AuraEnabled
    public static List<Open_Position__c> getMyOpenPositions(){
        //checking if athe user can access the case
        
        if(!Schema.SObjectType.Open_Position__c.isAccessible()){
            throw new AuraHandledException('You cannot access the Open Position object.');
        }
        
        List<Open_Position__c> openPositions = [SELECT Id, Job_Title__c	, Job_Description__c, salary__c  
                                                FROM Open_Position__c WHERE status__c='Open'];
        
        return openPositions;
    }
    
}